### ISSUE TITLE
[Improvement] Checking an object's class in tests

### ISSUE THREAD

**Issue by taraspogrebniak** [jlprat/Akka-Lunch-and-Learn-Sessions#1]
It is not a bug, but rather a tiny improvement (or even maybe a question of taste)

Source code: https://github.com/jlprat/Akka-Lunch-and-Learn-Sessions/blob/master/src/test/scala/io.github.jlprat.akka.lnl/intro/classic/TemperatureStatisticsTest.scala#L53

Suggestion

Instead of doing `futureAverageTemp.failed.futureValue.isInstanceOf[IllegalStateException]` it is also possible to do `futureAverageTemp.failed.futureValue shouldBe an[IllegalStateException]`. IMO it is more aligned with the idea of using matchers in scalatest

**Comment by jlprat** [comment]
Actually you are right

**Comment by jlprat** [comment]
Fixed
